jobs:
  build-documentation:
    if: github.repository == 'apache/flink'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
      with:
        ref: ${{ matrix.branch }}
    - continue-on-error: true
      name: Set branch environment variable
      run: "currentBranch=$(git branch --show-current)\n\necho \"flink_branch=${currentBranch}\"\
        \ >> ${GITHUB_ENV}\n\nif [ \"${currentBranch}\" = \"master\" ]; then\n  echo\
        \ \"flink_alias=release-1.20\" >> ${GITHUB_ENV}\nelif [ \"${currentBranch}\"\
        \ = \"release-1.19\" ]; then\n  echo \"flink_alias=stable\" >> ${GITHUB_ENV}\n\
        fi\n"
    - continue-on-error: true
      name: Build documentation
      run: 'docker run --rm --volume "$PWD:/root/flink" chesnay/flink-ci:java_8_11_17_21_maven_386
        bash -c "cd /root/flink && ./.github/workflows/docs.sh"

        '
    - continue-on-error: true
      name: Upload documentation
      uses: burnett01/rsync-deployments@5.2
      with:
        path: docs/target/
        remote_host: ${{ secrets.NIGHTLIES_RSYNC_HOST }}
        remote_key: ${{ secrets.NIGHTLIES_RSYNC_KEY }}
        remote_path: ${{ secrets.NIGHTLIES_RSYNC_PATH }}/flink/flink-docs-${{ env.flink_branch
          }}/
        remote_port: ${{ secrets.NIGHTLIES_RSYNC_PORT }}
        remote_user: ${{ secrets.NIGHTLIES_RSYNC_USER }}
        switches: --archive --compress --delete
    - continue-on-error: true
      if: env.flink_alias != ''
      name: Upload documentation alias
      uses: burnett01/rsync-deployments@5.2
      with:
        path: docs/target/
        remote_host: ${{ secrets.NIGHTLIES_RSYNC_HOST }}
        remote_key: ${{ secrets.NIGHTLIES_RSYNC_KEY }}
        remote_path: ${{ secrets.NIGHTLIES_RSYNC_PATH }}/flink/flink-docs-${{ env.flink_alias
          }}/
        remote_port: ${{ secrets.NIGHTLIES_RSYNC_PORT }}
        remote_user: ${{ secrets.NIGHTLIES_RSYNC_USER }}
        switches: --archive --compress --delete
    strategy:
      matrix:
        branch:
        - master
        - release-1.20
        - release-1.19
        - release-1.18
        - release-1.17
      max-parallel: 1
name: Build documentation
on:
  repository_dispatch:
    types: trigger-ga___docs.yml
