jobs:
  Trigger:
    if: github.repository == 'apache/flink'
    permissions:
      actions: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Trigger Workflow
      uses: actions/github-script@v7
      with:
        script: "github.rest.actions.createWorkflowDispatch({\n  owner: context.repo.owner,\n\
          \  repo: context.repo.repo,\n  workflow_id: 'nightly.yml',\n  ref: '${{\
          \ matrix.branch }}'\n})\n"
    strategy:
      matrix:
        branch:
        - master
        - release-1.20
        - release-1.19
        - release-1.18
name: Nightly trigger (beta)
on:
  repository_dispatch:
    types: trigger-ga___nightly-trigger.yml
