jobs:
  qa:
    container:
      image: mapohl/flink-ci:FLINK-34194
      options: --init --privileged
    name: Basic QA
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Flink Checkout
      uses: actions/checkout@v4
      with:
        persist-credentials: false
    - continue-on-error: true
      name: Initialize job
      uses: ./.github/actions/job_init
      with:
        jdk_version: ${{ inputs.jdk_version }}
    - continue-on-error: true
      name: Checkstyle
      uses: ./.github/actions/run_mvn
      with:
        maven-parameters: checkstyle:check -T1C
    - continue-on-error: true
      if: (success() || failure())
      name: Spotless
      uses: ./.github/actions/run_mvn
      with:
        maven-parameters: spotless:check -T1C
    - continue-on-error: true
      if: (success() || failure())
      name: License Headers
      uses: ./.github/actions/run_mvn
      with:
        maven-parameters: org.apache.rat:apache-rat-plugin:check -N
name: Pre-compile Checks
on:
  repository_dispatch:
    types: trigger-ga___template.pre-compile-checks.yml
permissions: read-all
